### ISSUE TITLE
Formulario para inserción de metodos de pesca

### ISSUE THREAD

**Issue by elenchuffe27** [jdrodas/PescaArtesanal#13]
Implementar formulario para generar reportes de método de pesca

**Comment by jdrodas** [comment]
Hola @elenchuffe27 , 

Este formulario ya se encontraba implementado al momento de generar este incidente. Sin embargo, existen otros pendientes sobre la tabla "Metodos de Pesca" que podemos aprovechar.

Utilizaré este incidente para hacerle seguimiento a la implementación de la inserción de los métodos de pesca
