### ISSUE TITLE
Actualizacion de las listas

### ISSUE THREAD

**Issue by LeonStyven** [jdrodas/PescaArtesanal#2]
Las listas no se actualizan automáticamente luego de hacer un borrado o actualización de los datos.

**Comment by jdrodas** [comment]
Hola @LeonStyven , muchas gracias por tu reporte de incidente.

Efectivamente esta situación se está presentando cuando las listas de una forma abierta no se están actualizando cuando una de las acciones CRUD sobre la misma tabla se está haciendo en otra forma.

Por ejemplo, si se tiene abierta la forma de borrado de municipio, la lista que se encuentra en ella no se actualiza cuando se inserta o se actualiza un municipio en cualquiera de las otras formas. Mientras la forma esté abierta, el control del tipo listbox no se está actualizando.

Esto se debe a que se ha implementado una interfaz pseudo-MDI (_Multiple Document Interface_), en la que se comporta como tal, pero no cumple el funcionamiento como dice la documentación. Esta versión simplificada hace que algunos eventos que estarían disponibles para garantizar que los controles se refresquen correctamente, no funcionen de la manera esperada.

Un "Workaround" que resuelve este comportamiento, lo implementamos en el método "AbrirFormulario" del Formulario "Principal". Invertimos la condición de tal manera que si estaba abierto, se cierre y luego se procede a abrirlo nuevamente:

![image](https://user-images.githubusercontent.com/29258977/226508088-47157ec5-2a5e-4aac-9c19-fde08e53e39b.png)

Lejos de ser la solución adecuada, pero nos permite enfocarnos en los temas propios del proyecto que son todas las interfaces a las acciones CRUD. Posteriormente se podrá implementar una solución más elegante a este problema.
