### ISSUE TITLE
Cambio de métodos que retornen lista de string a su tipo de dato

### ISSUE THREAD

**Issue by modsiw-mona** [jdrodas/PescaArtesanal#3]
En la carpeta PescaArtesanal_WindowsForm, ingresamos a la otra carpeta PescaArtesanal_WindowsForm y a la clase AccesoDatos.cs. 
El método ObtieneNombresDepartamentos(), debería estar transformando los datos resultantes a la clase Departamento. Ya que trabajar con los string de los nombres de departamento, en vez del objeto departamento, es una mala práctica.

**Comment by jdrodas** [comment]
Gracias @modsiw-mona por tu recomendación.

Para contextualizar, Este es el método referenciado:

![image](https://user-images.githubusercontent.com/29258977/225496455-73843465-c650-4825-bf94-4b24dd83ebe5.png)

Hay dos razones por las que implementamos la solución de esta manera:

**1. Utilizar justo lo necesario.**
Este método en particular solo es utiliza para traer los nombres de los departamentos, por lo que mapearlo al objeto "Departamento" traería adicionalmente la columna "Codigo" que no la utilizaríamos. En tablas pequeñas no se siente el impacto pero se convierte en problema con tablas de cientos de millones de registros.

**2. Patrón Alta Cohesión y Bajo Acoplamiento.**
Estamos reduciendo la dependencia de las clases de "FrontEnd" (Los Formularios) de las clases del "BackEnd", en un intento por implementar una Alta Cohesión y un Bajo Acoplamiento. Si el método "ObtieneNombresDepartamentos()" Entregara la totalidad del objeto, la clase del Formulario tendría que implementar lógica para extraer solamente el nombre del departamento, que es lo que en este caso necesitamos.

Es una buena práctica sin embargo, Utilizar una nomenclatura en el código más acorde al propósito de los miembros de la clase.

Aprovecharé este incidente para renombrar el método en cuestion a "ObtieneListaNombresDepartamentos" y actualizar sus referencias.
