### ISSUE TITLE
Separador punto decimal

### ISSUE THREAD

**Issue by SebasSanchezJKR** [jdrodas/PescaArtesanal#5]
El punto no es leído como el separador decimal para la cantidad de pescado

**Comment by jdrodas** [comment]
Hola @SebasSanchezJKR , gracias por el registro de este incidente.

Para darle solución, identificamos el separador decimal que está registrado en la cultura utilizada por la configuración regional del computador que ejecuta la aplicación:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/29258977/231534245-8bb625ab-c8f9-4611-8b4e-0d44866b7b07.png">

Luego, al convertir el número ingresado para la cantidad de pescado, se hace el reemplazo correspondiente:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/29258977/231534852-ee37499a-4dcb-4b44-89c2-ab0db3e92658.png">
