### ISSUE TITLE
Reporte Añadir métodos

### ISSUE THREAD

**Issue by sboteroarango** [jdrodas/PescaArtesanal#6]
Se debe validar que el nuevo método agregado no exista

**Comment by jdrodas** [comment]
Hola @sboteroarango , gracias por tu registro de incidente.

Esta situación se presenta también con Cuencas y Departamentos, por lo que se realizará el cambio en los métodos de Actualizar para cada una de estas entidades.

Para Departamentos:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/29258977/231542083-6575065e-9be8-4251-81f2-84c95868e979.png">

Para Cuencas:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/29258977/231542915-440cbe5d-fd76-4e04-8c51-2dcf233741d8.png">

Para Métodos:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/29258977/231544487-3c90b21a-ddb4-4d6d-8b70-d9b3f220817a.png">
